[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
crowdfundingdapp = "HDcBuaDqeqvMoDFH69FF3Fr92F71w2CBhCM7BT2uY6GA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
