[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
crowdfundingdapp = "5KJrdYJAaTaxu4WFcktxp7wjCfLGa4xujvFSCK7HLpDW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
